# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

image: node:7.8.0

cache:
  paths:
  - node_modules/
  - .yarn

stages:
- test
- deploy

test:
  stage: test
  script:
  - yarn config set cache-folder .yarn
  - yarn install
  - npm run test
#  artifacts:
#    paths:
#    - node_modules/
#    - public

deploy:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  only:
  - master
